### PR TITLE
Update nodejs7 to 7.4.0

### PR DESCRIPTION
**Pull request by Qantas94Heavy**

### CODE REVIEW

**Comment by Qantas94Heavy** [comment]
@AdamMajer how should a patch for nodejs7 only be applied? nodejs/node#10649 seems to be causing a build failure for nodejs7.

**Comment by AdamMajer** [comment]
Well, you can put it in the common directory so it gets copied the same to all versions, then add something like,

Patch70:   my_nodejs7.patch

but in the %patch section, just have it in an %if block, like

%if {{node_version_major}} == 7
%patch70 -p1
%endif

There shouldn't be many of these patches and they should go away rather quickly, so just group them, so Patch40-49 -> nodejs4, Patch70-79 -> nodejs7, etc. this way only one %if block.

The downside of course is that the patch ends up in all nodejs source versions on upload, but it's just not applied.

- Adam

PS. `quilt header -e` is a nice way to describe what a patch does, who authored the patch and for what purpose. It edits the header of the current patch. IMO, it's much better than having a description all over the spec file.

**Comment by AdamMajer** [comment]
thanks

**Comment by AdamMajer** [comment]
I've updated the change a little bit so it doesn't need another sed replacement.

**Comment by Qantas94Heavy** [comment]
Thanks, but doesn't that fail with the other `nodejsX` packages (where it will still complain about the missing patch even with the conditional macro)?

If my idea is too messy we could just stick with your original idea instead.

**Comment by AdamMajer** [comment]
On 01/12/2017 08:45 AM, Karl Cheng wrote:
> Thanks, but doesn't that fail with the other |nodejsX| packages (where
> it will still complain about the missing patch even with the conditional
> macro)?

Ah yes, one stupid service is complaining about it :/

> If my idea is too messy we could just stick with your original idea instead.

The problem with your idea is that structural sections of spec file are
ending up in other places, which means it's no longer possible to just
read the spec file and know where all the parts are.

I'll think about this, maybe there is a more cleaver solution.

- Adam

**Pull request merged**
