### PR TITLE
Allow building for Fedora in the OBS

### PR DESCRIPTION
**Pull request by cryptomilk**
Test build: https://build.opensuse.org/package/show/home:gladiac:branches:devel:languages:nodejs/nodejs15

### CODE REVIEW

**Comment by AdamMajer** [comment]
This looks good. Thank you.

I see that the build is failing because of the update-alternatives issue so I'll wait before merging. The simplest may be to build with `libalternatives` instead of `update-alternatives` and then that would sidestep the absolute links problems? What do you think? That would require changes in `nodejs-common/nodejs-common.spec` to require it for Fedora too in addition to TW.

Aside note, nodejs15 is EOL and nodejs16 is current and will be LTS later this year. nodejs14 is also in active LTS now. If you can use nodejs16 and fallback on nodejs14 if necessary.

**Comment by cryptomilk** [comment]
I will switch to nodejs16 once you fixed the _constraints file so it builds on Leap ... ;-)

New build is running.

**Comment by AdamMajer** [comment]
I'm now fixing these issues by changing debug information from `-g` (which is `-g2`) to `-g1`. Basically, v8 is exploding the debug information so much that it results in more and more memory usage. This was the only way to compile it already on 32-bit arches, but even in 64-bit arches it's now causing delays due to disk usage and memory requirements for building.

With changes to debug level, it will be possible to reduce _constraints while fixing these OOM issues during link.

**Comment by cryptomilk** [comment]
The branch is ready for merge now.

**Comment by AdamMajer** [comment]
Thank you. Looks good. Can you also add the condition for `nodejs-common/nodejs-common.spec` regarding libalternatives?

As-is, the binary nodejs15 RPM will have a missing runtimes dependency and it will not run via `/usr/bin/node` but only via `/usr/bin/node15`. When nodej-common package is built with libalternatives, everything will then work as expected.

**Comment by AdamMajer** [comment]
Thank you. I will merge shortly.

Just wondering, do you plan on using these node packages on Fedora? Would it benefit in adding them to build targets in the nodejs devel project?

**Comment by cryptomilk** [comment]
My plan would be to build signal-desktop for Fedora too, see https://build.opensuse.org/project/show/network:im:signal

I'm just done with packaging nodejs-electron for openSUSE. This was the last part not built from source.

**Comment by cryptomilk** [comment]
I've tried nodejs16 with signal-desktop again, it fails to build node-sass. So upstream needs to move to a newer node-sass first.

**Pull request merged**
