### PR TITLE
Fix boo#1192962

### PR DESCRIPTION
**Pull request by yecril71pl**

### CODE REVIEW

**Comment by AdamMajer** [comment]
Thanks, but nodejs-common doesn't require npm to function. nodejs can function just fine without npm. If you need npm, please install it. You can install default npm by `zypper in npm-default`

**Comment by yecril71pl** [comment]
Have you read the [bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1192962)?  The command `/usr/bin/npx`, as installed with `nodejs-common`, requires `npm` to run.  Installing a broken executable is wrong.  It is a waste of time for everybody.

**Comment by AdamMajer** [comment]
Yes. Last time I tried to fix this, I came upon "legacy" and had to revert it.

But introducing circular dependencies makes independent subpackages pointless. Let me think how to fix it without breaking older installations. Maybe moving these symlinks to actual `npmX` packages would make more sense

**Comment by yecril71pl** [comment]
> Yes. Last time I tried to fix this, I came upon "legacy" and had to revert it.
> 
> But introducing circular dependencies makes independent subpackages pointless. Let me think how to fix it without breaking older installations. Maybe moving these symlinks to actual `npmX` packages would make more sense

`/usr/bin/npx` is not a symbolic link, it is an actual executable that calls `libalternatives` to decide what `npx` really is.  I understand that `npm` is not a circular dependency because it is a feature, not a package.

```sh
pkcon get-details npm
```

**Comment by AdamMajer** [comment]
It's actually a hardlink to /usr/bin/node. This means it *can* be replaced by a symlink. Problem is that this is tricky due to way that SLES/Leap is updated.

**Comment by yecril71pl** [comment]
> It's actually a hardlink to /usr/bin/node. This means it _can_ be replaced by a symlink. Problem is that this is tricky due to way that SLES/Leap is updated.

I fail to see how using a symbolic link would address the problem at hand.

**Comment by AdamMajer** [comment]
Well,

1. remove /usr/bin/np{m,x} from nodejs-common, since this is wrong place for it
2. each /usr/bin/npm{14,16,...} package, and npm-defaults, contains a link instead

Then if you BR: /usr/bin/npm, it will actually work.

**Comment by yecril71pl** [comment]
> Well,
> 
> 1. remove /usr/bin/np{m,x} from nodejs-common, since this is wrong place for it
> 2. each /usr/bin/npm{14,16,...} package, and npm-defaults, contains a link instead
> 
> Then if you BR: /usr/bin/npm, it will actually work.

Do you envisage killing the self-made `npx` binary and replacing it with a regular alternatives mechanism?  Should the command `node` stay in the package `nodejs-common`?  For what purpose?  Why is it different from `npx`?

**Comment by AdamMajer** [comment]
/usr/bin/node runs the correct node binary which you can see https://github.com/AdamMajer/nodejs-packaging/blob/master/nodejs-common/node.c . The mechanism is rather simple -- run default version unless specific version is in the call chain, then stick with the specific version.

This allows you to build binary modules with `node-gyp` for every node version you have installed independently. `node-gyp` re-executes node as /usr/bin/node so if you run `node10` explicitly while having `node14` also installed as default, you probably want node-gyp to use `node10` to build the binary module. That is the purpose.

**Comment by yecril71pl** [comment]
Superseded by #43

**Pull request closed without merging**
